version: "3"
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  db:
    image:  postgres
    restart: always
    ports:
      - "5532:5432"
    environment:
       POSTGRES_PASSWORD: pass123
